### ISSUE TITLE
【BUG】Project update to 1.12.x causes WD issues

### ISSUE THREAD

**Issue by UzkiS** [bdunderscore/modular-avatar#1533]
Normal projects, updating MA to 1.12.x will cause WD-like abnormalities in gestures and facial expressions (gestures will not be triggered, facial expressions are triggered by gestures but will not be restored)
Roll back MA to 1.11.x and everything will return to normal
I think it might be related to the update of Merge Animator.

Information about Project and the components I think will be affected:
MA Merge animator
VRCFury Write Default Fixed (Set to ON)
VRCFury Toggle
DynamicGesture + gesture control props
(Avatar made item switches and some gesture-related MA plugins for Grus using VRCFury + MA)

So far, I have not found a recurrence rule from scratch. Once I locate the steps that must be recurring, I will reply

(Using machine translation)

**Comment by bdunderscore** [comment]
Please confirm the precise version you’re using as I fixed a bug similar to this in 1.12.1. I will also need a reproduction case to investigate further.

**Comment by bdunderscore** [comment]
This sounds like it might be a VRCFury bug. There were some behavior changes in MA that might be confusing it however. I’ll reach out to Senky once I have a repro.

**Comment by bdunderscore** [comment]
This is probably the same as #1541 and will probably be fixed in the next release.

**Comment by UzkiS** [comment]
Unfortunately, I updated to 1.12.3 and re-switched the VRCFury Fix Write Defaults switch from Force On to Auto (detected as Auto = WD on), the problem still persists, and I can't find the cause. If this happens again next time I create a new project, I will report the steps again
